### PR TITLE
Refactor filters/Helpers.java and filters/Kernels.java

### PR DESCRIPTION
**Pull request by priyanshul-govil**
Normal refactoring. Details in commits.

### CODE REVIEW

**Comment by priyanshul-govil** [comment]
@viveknathani Normal design refactoring, so merging on my own. Although, I still need a code review.

**Comment by viveknathani** [comment]
@priyanshul-govil, every commit seems fine to me except [one](https://github.com/secur3dit/app/pull/18/commits/96b8232ca80a7adca94005ef379cb3b44345d152).

My understanding so far has been that when we do not declare an access specifier, in a class that is a part of a package, the members get the access specification of `package-private` which is what I had indented for `Helpers.java`.  Correct me if I have misunderstood.

I did not want (and cannot see) this class being used outside the scope of this module. Let me know if you think differently. Otherwise, we should roll back to having no access specifier.

**Comment by priyanshul-govil** [comment]
> @priyanshul-govil, every commit seems fine to me except [one](https://github.com/secur3dit/app/pull/18/commits/96b8232ca80a7adca94005ef379cb3b44345d152).
> 
> My understanding so far has been that when we do not declare an access specifier, in a class that is a part of a package, the members get the access specification of `package-private` which is what I had indented for `Helpers.java`. Correct me if I have misunderstood.
> 
> I did not want (and cannot see) this class being used outside the scope of this module. Let me know if you think differently. Otherwise, we should roll back to having no access specifier.

@viveknathani Class access specifier defines the visibility of the class. No access specifier for a class declaration means that the class will be visible inside the package.
However, this has no effect on the methods' visibility. Although the methods are `static` and thus intended to be called from the class scope and not the object scope, and the methods are by *default* `public`, it is always better to explicitly mention this.
A good enough example should be `public static void main(...)`.

Also note: `private static` methods are also valid, and only accessible from class scope within the class.

**Comment by viveknathani** [comment]
@priyanshul-govil Why do we want to make each member's access specification `public`?

The default access specifier for the members of a class inside a package is `package-private` which serves what I intend to do. Refer [this](https://docs.oracle.com/javase/tutorial/java/javaOO/accesscontrol.html). Or let me know if I am not understanding anything. 

My intention is simple. I don't want the methods of class being used outside the package. Using `public` does not help me achieve that.

**Comment by priyanshul-govil** [comment]
> @priyanshul-govil Why do we want to make each member's access specification `public`?
> 
> The default access specifier for the members of a class inside a package is `package-private` which serves what I intend to do. Refer [this](https://docs.oracle.com/javase/tutorial/java/javaOO/accesscontrol.html). Or let me know if I am not understanding anything.
> 
> My intention is simple. I don't want the methods of class being used outside the package. Using `public` does not help me achieve that.

Alright, I read about it. What you're saying makes sense.
You can deal with this in a new commit. Also, we would need an update in access specifiers of c*rypto/Helpers.java* and *crypto/Constants.java*

**Pull request merged**
