### PR TITLE
chore: Initialize directory structure

### PR DESCRIPTION
**Pull request by priyanshul-govil**
This is the first commit for the crypto/ directory. It creates the
necessary structure and the required files. The following files
have been added:
  1. AES.java - Implements the overall encryption.
  2. Helpers.java - Contains methods required for AES.
  3. Constants.java - Contains the lookup tables (eg: S-box).
  4. CTR.java - Required for applying AES on more than 1 block.
Further commits should refer to this for the basic structure. This
implementation of AES will be using the CTR mode of operation.

### CODE REVIEW

**Comment by priyanshul-govil** [comment]
Post merging this PR, we would need an update in the [File Structure](https://github.com/secur3dit/standard/blob/main/FILE_STRUCTURE.md).

**Comment by viveknathani** [comment]
This commit seems more apt for the "chore" category than the "feat" category. Let me know if you think otherwise. If not, make the change. If making the change seems difficult (as the edits will have to be reflected in your local copy), we can leave it at this and I will merge.

**Comment by viveknathani** [comment]
> 
> 
> Post merging this PR, we would need an update in the [File Structure](https://github.com/secur3dit/standard/blob/main/FILE_STRUCTURE.md).

All right, I will make a PR for this.

**Comment by priyanshul-govil** [comment]
Updated the commit details.

**Pull request merged**
